apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-grpc
  labels:
    app: net-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      service: net-grpc
  template:
    metadata:
      labels:
        app: net-sample
        service: net-grpc
    spec:
      containers:
        - name: net-webapi
          image: netsample.azurecr.io/grpc-service:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: net-grpc
  labels:
    app: net-sample
    service: net-grpc
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: net-grpc
