apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-webapi
  labels:
    app: net-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      service: net-webapi
  template:
    metadata:
      labels:
        app: net-sample
        service: net-webapi
    spec:
      containers:
        - name: net-webapi
          image: netsample.azurecr.io/web-api:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: net-webapi
  labels:
    app: net-sample
    service: net-webapi
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
  selector:
    service: net-webapi