version: '3.4'

services:
  grpc-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
 #     - "443"
   # volumes:
    #  - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  web-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
  #    - "443"
   # volumes:
   #   - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
   #   - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
