version: '3.9'

services:
  net-grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
   # ports:
    #  - "80"
    #  - "443"
   # volumes:
    #  - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  net-webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
  #    - "443"
   # volumes:
   #   - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
   #   - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
